### ISSUE TITLE
Animation on scroll

### ISSUE THREAD

**Issue by Gerarddancekassi** [Gerarddancekassi/planetexpress-grid#2]
I don't know JS yet yet so I can't really do this but it'll be nice to have the ship fly across the screen as the user scrolls

**Comment by abitsalihu** [comment]
@Gerarddancekassi Hey I would like to help you with this issue. :)
Also as I was checking out the website I noticed you have some extra margin on the right side  and the body overflows (you can see a scroll bar at the bottom which shouldn't be there), below is a screenshot of the problem, I will fix this as I work on that animation.

<img width="1437" alt="Screen Shot 2022-09-17 at 23 45 23" src="https://user-images.githubusercontent.com/94648837/190877392-c728c129-5dfa-4ed8-bf68-627a867708e9.png">

**Comment by Gerarddancekassi** [comment]
Oh nice, okay. I'm new to GitHub so I don't know how to allow access to the css

**Comment by Gerarddancekassi** [comment]
Thank you for this

**Comment by Gerarddancekassi** [comment]
I added you to the repo

**Comment by abitsalihu** [comment]
@Gerarddancekassi  That's okay, I'll give you a fast walkthrough of how this will work. :)

First on the top right side of ur screen you can assign me on this issue (This is done so other people that check this issue out will know that someone is working on it).

Next tomorrow after I work on this and I make the changes I will make a pull request where you will be able to see the changes I did on the code(I will show you how to go through this process tomorrow after I make the pull request)

If you have discord, I would happily help you through all of this on call tomorrow. :)

**Comment by abitsalihu** [comment]
@Gerarddancekassi I saw that you added me on the repo, I will decline that as you don't need to do that.(with me or with anyone else, as you don't want other people to push changes you your project without you seeing the changes and approving them).

**Comment by Gerarddancekassi** [comment]
okay I think I was able to assign you to it.
